---
name: springframework-demo
sourceCode:
  type: git
  url: https://github.com/pranavgaikwad/migtools-getting-started
  branch: eval
  path: spring-framework-migration
targets:
  - spring6
  - cloud-readiness
programmingLanguage: Java

